(#121) Add latex representation to formulas from chapter 8 of NEN-EN 1992-1-1+C2:2011
Blueprints-org/blueprints pull request #122
Opened 2024-01-26 11:05 UTC by PetervWestrienen

## Description
Add latex representation to formulas from chapter 8 of NEN-EN 1992-1-1+C2:2011

Fixes (#121)

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes

![image](https://github.com/Blueprints-org/blueprints/assets/76411057/ddd6b225-7cd2-4def-8b56-d33cc24ed735)
![image](https://github.com/Blueprints-org/blueprints/assets/76411057/11006ffd-4dae-4585-9a20-f86acd9f9ad7)
![image](https://github.com/Blueprints-org/blueprints/assets/76411057/fe12d783-4db4-485c-be44-92b64c99d5c1)
![image](https://github.com/Blueprints-org/blueprints/assets/76411057/f52e174f-1d44-4f8c-9ddf-798d4fa65545)
![image](https://github.com/Blueprints-org/blueprints/assets/76411057/adb2683e-a1b3-40d7-9442-dcc07724ab45)
![image](https://github.com/Blueprints-org/blueprints/assets/76411057/171b8e24-a714-4456-8eca-d34918879aaa)
![image](https://github.com/Blueprints-org/blueprints/assets/76411057/318cc06b-257c-4ff0-8fd7-66152d3e1a83)
![image](https://github.com/Blueprints-org/blueprints/assets/76411057/0fa1e3c1-55a0-4d5d-9909-73a47cfcc79f)
![image](https://github.com/Blueprints-org/blueprints/assets/76411057/e3fc7b3d-c5ce-4818-b809-cc7691a4c590)

2024-03-27 23:49 UTC, egarciamendez commented
8.2:
$f_{bd} = 2.25 \cdot \eta_1 \cdot \eta_2 \cdot f_{ctd} = 2.25 \cdot 1.00 \cdot 1.00 \cdot 20.00 = 45.00$
![afbeelding](https://github.com/Blueprints-org/blueprints/assets/44614728/e41b08fc-09ba-4027-8ab1-e25104d852ac)

8.3:
$l_{b,rqd} = \frac{Ø}{4} \cdot \frac{\sigma_{sd}}{f_{bd}} = \frac{12}{4} \cdot \frac{435}{2.9} = 450.00$

8.4:
![afbeelding](https://github.com/Blueprints-org/blueprints/assets/44614728/c0c678ab-eef1-4eb2-86f2-fb5d242152a3)

8.6:
![afbeelding](https://github.com/Blueprints-org/blueprints/assets/44614728/4fdb8e59-7038-4cab-8316-d98665cf4a0c)

8.7:
![afbeelding](https://github.com/Blueprints-org/blueprints/assets/44614728/aab95a75-ef74-436c-af31-52145cea6329)


8.10:
![afbeelding](https://github.com/Blueprints-org/blueprints/assets/44614728/bee1e4a6-6d4f-42bf-9075-109151d6b6a1)

Subformula 8.10:
![afbeelding](https://github.com/Blueprints-org/blueprints/assets/44614728/ec484149-f4f8-4f9c-b91a-9ce0198d64ea)

8.11:
![afbeelding](https://github.com/Blueprints-org/blueprints/assets/44614728/789daa25-5d87-47b9-8ee5-8725342fdc17)

2024-03-27 23:50 UTC, egarciamendez approved these changes
Ready to 🚢

2024-03-28 07:55 UTC, bro-wi requested changes

2024-03-28 07:55 UTC, bro-wi commented on blueprints/codes/eurocode/nen_en_1992_1_1_c2_2011/chapter_8_detailing_of_reinforcement_and_prestressing_tendons/formula_8_2.py
> +            equation=r"\begin{matrix} 1.0 & \text{voor }Ø ≤ 32 \\ (132 - Ø) / 100 & \text{voor }Ø > 32  \end{matrix}",
shoulnd't we use english?

```suggestion
            equation=r"\begin{matrix} 1.0 & \text{for }Ø ≤ 32 \\ (132 - Ø) / 100 & \text{for }Ø > 32  \end{matrix}",
```

2024-03-28 14:48 UTC, merged