Add formula 5.5 from NEN-EN-1993.5:2008
Blueprints-org/blueprints pull request #195
Opened 2024-03-19 14:07 UTC by Klaassicking

## Description

Add formula 5.5 from NEN-EN-1993.5:2008

$V_{pl,Rd} = \frac{A_v f_y}{\sqrt{3} \gamma_{M0}}$

Fixes #194 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes

2024-03-22 08:20 UTC, bro-wi requested changes
Nice work and nice to see you are doing so many PR's!

Main concern from my part is getting all the units correct, because now it is not really consistent IMO.

cheers.

2024-03-22 08:20 UTC, bro-wi commented on blueprints/codes/latex_formula.py
> +def fraction(numerator: str | float, denominator: str | float) -> str:
I would rename this function to be more explicit, e.g. `latex_fraction`

2024-03-22 08:20 UTC, bro-wi commented on blueprints/codes/eurocode/nen_en_1993_5_2008/chapter_5_ultimate_limit_states/formula_5_5.py
> +        """(Vpl,Rd) Calculate plastic shear resistance in [kN/m] based on formula 5.5 from NEN-EN 1993-5:2007(E) art. 5.2.2(4).
```suggestion
        """(Vpl,Rd) Calculate plastic shear resistance in [kN] based on formula 5.5 from NEN-EN 1993-5:2007(E) art. 5.2.2(4).
```

mm2*N/mm2 / (unitlesss) ==> N

2024-03-22 08:20 UTC, bro-wi commented on blueprints/codes/eurocode/nen_en_1993_5_2008/chapter_5_ultimate_limit_states/formula_5_5.py
> +    ) -> KNM:
This is not a moment

```suggestion
    ) -> KN_M:
```

or even better (IMO)

```suggestion
    ) -> KN:
```

2024-03-22 08:20 UTC, bro-wi commented on tests/codes/eurocode/nen_en_1993_5_2008/chapter_5_ultimate_limit_states/test_formula_5_5.py
> +    def test_latex_output(self) -> None:
use parametrize here, now the test possible will fail in the first check and will leave other un noticed. see also Sina's comment on #191 in that regard

2024-03-22 08:20 UTC, bro-wi commented on tests/codes/eurocode/nen_en_1993_5_2008/chapter_5_ultimate_limit_states/test_formula_5_5.py
> +        expected = 40000 / np.sqrt(3) / 1000
```suggestion
        expected = 40 / np.sqrt(3)
```

2024-03-22 08:20 UTC, bro-wi commented on tests/codes/eurocode/nen_en_1993_5_2008/chapter_5_ultimate_limit_states/test_formula_5_5.py
> +        # Expected result, manually calculated
not really 'manually' calculated isn't it?

2024-03-22 08:20 UTC, bro-wi commented on tests/codes/test_latex_formula.py
> +    """Test the latex_fraction function."""
```suggestion
    """Test the latex_fraction function."""
```
This name (latex_fraction) is much better, but it it is different from the function you are testing.

2024-03-23 17:06 UTC, egarciamendez approved these changes
Suggestions from Wichard have been implemented. 😉 🚀

2024-03-23 17:10 UTC, merged