(#198) Add formula 5.7 from NEN-EN-1993.5:2008
Blueprints-org/blueprints pull request #199
Opened 2024-03-19 17:15 UTC by Klaassicking

## Description

Add formula 5.7 from NEN-EN-1993.5:2008 

$V_{b,Rd} = \frac{\left(h - t_f \right) t_w f_{bv}}{\gamma_{M0}}$

Fixes #198 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes

2024-03-24 17:42 UTC, egarciamendez approved these changes
Already fixed according to the other formulas. 🚀

2024-03-25 08:01 UTC, bro-wi requested changes

2024-03-25 08:01 UTC, bro-wi commented on tests/codes/eurocode/nen_en_1993_5_2008/chapter_5_ultimate_limit_states/test_formula_5_7.py
> +        f_bv = 300  # kN
```suggestion
        f_bv = 300  # MPA
```

2024-03-25 08:01 UTC, bro-wi commented on tests/codes/eurocode/nen_en_1993_5_2008/chapter_5_ultimate_limit_states/test_formula_5_7.py
> +        f_bv = 300  # kN
MPA

2024-03-25 13:10 UTC, egarciamendez commented on blueprints/codes/eurocode/nen_en_1993_5_2008/chapter_5_ultimate_limit_states/formula_5_7.py
> +        )
How about a plain old ValueError for this one?

2024-03-27 17:38 UTC, merged