168 feature request add formula 516 from nen en 1992 1 1 c2 2011
Blueprints-org/blueprints pull request #275
Opened 2024-05-22 10:06 UTC by MaartenBW

## Description

Please write a description of the changes you made here.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

## Checklist:

- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] New and existing unit tests pass locally with my changes

2024-05-22 11:19 UTC, bro-wi approved these changes
Nice implementation. Only some small comments on my part.

2024-05-22 11:19 UTC, bro-wi commented on blueprints/codes/eurocode/nen_en_1992_1_1_c2_2011/chapter_5_structural_analysis/formula_5_14.py
> +            or :class: `Form5Dot15EffectiveLengthUnbraced`.
I think we have to add an 'integration' test to support this always.

2024-05-22 11:19 UTC, bro-wi commented on blueprints/codes/eurocode/nen_en_1992_1_1_c2_2011/chapter_5_structural_analysis/formula_5_15.py
> +        l : M
```suggestion
        height : M
```

2024-05-22 11:19 UTC, bro-wi commented on blueprints/codes/eurocode/nen_en_1992_1_1_c2_2011/chapter_5_structural_analysis/formula_5_15.py
> +    def __init__(self, k_1: DIMENSIONLESS, k_2: DIMENSIONLESS, height: M) -> None:
I think it is a good choice to change l (lower L) into 'height'!

2024-05-22 12:22 UTC, MaartenBW commented on blueprints/codes/eurocode/nen_en_1992_1_1_c2_2011/chapter_5_structural_analysis/formula_5_15.py
> +        l : M
Fixed in PR #272

2024-06-02 22:29 UTC, egarciamendez requested changes
Found a lot of errors in the docs and latex representation. Need to fix before merging, I'm fixing those already but it's getting kind of late. Will continue tomorrow.

2024-06-02 22:29 UTC, egarciamendez commented on tests/codes/eurocode/nen_en_1992_1_1_c2_2011/chapter_5_structural_analysis/test_formula_5_15.py
Not the same as the eurocode 
![afbeelding](https://github.com/Blueprints-org/blueprints/assets/44614728/57d8561c-d32a-4b3c-8862-f162188d9a21)

![afbeelding](https://github.com/Blueprints-org/blueprints/assets/44614728/c605da65-950e-46da-acbd-2dd690363c62)

2024-06-02 22:29 UTC, egarciamendez commented on tests/codes/eurocode/nen_en_1992_1_1_c2_2011/chapter_5_structural_analysis/test_formula_5_16.py
Same goes for this one.
![afbeelding](https://github.com/Blueprints-org/blueprints/assets/44614728/0d9d2ba4-a236-4754-98e6-cb2828d7f29e)
![afbeelding](https://github.com/Blueprints-org/blueprints/assets/44614728/ba0fdecc-7aa3-4c62-835a-99f9ff51c3cb)

2024-06-03 19:26 UTC, egarciamendez approved these changes
ready after some fixes

2024-06-03 19:27 UTC, merged