#36 Added formula 6.1 and included .idea/ folder (Pycharm) to .gitignore
Blueprints-org/blueprints pull request #37
Opened 2023-12-03 13:48 UTC by johan-tuls

## Description

- [ ] Added formula 6.1
![image](https://github.com/Blueprints-org/blueprints/assets/120473756/d507f371-e7de-40e8-ab0a-8a58b6fc871c)
- [ ] Added .idea/ to .gitignore

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] New and existing unit tests pass locally with my changes

2023-12-03 17:49 UTC, egarciamendez commented on blueprints/codes/eurocode/nen_en_1992_1_1_c2_2011/chapter_6_ultimate_limit_state/formula_6_1.py
> +            [V_ccd] Design value of the shear force component in the compression area in case of a change in height [kN].
Vccd

2023-12-03 17:53 UTC, egarciamendez commented on blueprints/codes/eurocode/nen_en_1992_1_1_c2_2011/chapter_6_ultimate_limit_state/formula_6_1.py
> +        if v_rd_s < 0:
I suppose shear could be either negative or positive.

2023-12-03 19:17 UTC, egarciamendez requested changes

2023-12-03 19:17 UTC, egarciamendez commented on blueprints/codes/eurocode/nen_en_1992_1_1_c2_2011/chapter_6_ultimate_limit_state/formula_6_1.py
> +        """
add Return ;-)

2023-12-04 05:30 UTC, johan-tuls commented on blueprints/codes/eurocode/nen_en_1992_1_1_c2_2011/chapter_6_ultimate_limit_state/formula_6_1.py
> +        NEN-EN 1992-1-1+C2:2011 art.6.1(2) - Formula (6.1)
added docstring

2023-12-04 21:44 UTC, egarciamendez approved these changes
🚀 let's merge

2023-12-04 21:45 UTC, merged